kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: HEKETI_CLI_SERVER
  restuser: ""
  secretNamespace: ""
  secretName: ""
allowVolumeExpansion: true
